-- AlterTable
ALTER TABLE `asset` ADD COLUMN `s3Bucket` VARCHAR(191) NULL,
    ADD COLUMN `s3Key` VARCHAR(191) NULL,
    ADD COLUMN `storageType` VARCHAR(191) NOT NULL DEFAULT 'local',
    ADD COLUMN `uploadedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `orthomosaic` ADD COLUMN `s3Bucket` VARCHAR(191) NULL,
    ADD COLUMN `s3Key` VARCHAR(191) NULL,
    ADD COLUMN `s3TilesetKey` VARCHAR(191) NULL,
    ADD COLUMN `storageType` VARCHAR(191) NOT NULL DEFAULT 'local';

-- CreateIndex
CREATE INDEX `Asset_s3Key_idx` ON `Asset`(`s3Key`);
